### ISSUE TITLE
There is not strategy parmeters input tab. Test stopped. Opencorrect page please/ Error:Could not find any strategy with parameters among the indicators. Add it to the chat and try again.

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#109]
There is not strategy parameters input tab. Test stopped. Open correct page please

Error:Could not find any strategy with parameters among the indicators. Add it to the chat and try again.

![截圖 2023-04-06 下午10 00 54](https://user-images.githubusercontent.com/18544298/230400977-18803285-bc6c-4380-97a1-d7366fdbd30e.png)

![截圖 2023-04-06 下午10 00 58](https://user-images.githubusercontent.com/18544298/230400997-436d8d25-21aa-450f-a12d-d4bdcabc8e27.png)

**Comment by VincenzoUrso** [comment]
i see changes in the tabs section, can't find other changes

<div class="tabs-qk6xG5kt"><div class="scroll-wrap-JlIG6zP0 size-small-JlIG6zP0" data-name="underline-tabs-buttons"><div id="id_indicator-properties-dialog-tabs_tablist" role="tablist" aria-orientation="horizontal" class="underline-tabs-JlIG6zP0"><button id="inputs" role="tab" tabindex="0" aria-selected="true" data-id="indicator-properties-dialog-tabs-inputs" class="underline-tab-asACDJHq size-small-asACDJHq selected-asACDJHq">Inputs</button><button id="properties" role="tab" tabindex="-1" aria-selected="false" data-id="indicator-properties-dialog-tabs-properties" class="underline-tab-asACDJHq size-small-asACDJHq">Properties</button><button id="style" role="tab" tabindex="-1" aria-selected="false" data-id="indicator-properties-dialog-tabs-style" class="underline-tab-asACDJHq size-small-asACDJHq">Style</button><button id="visibilities" role="tab" tabindex="-1" aria-selected="false" data-id="indicator-properties-dialog-tabs-visibilities" class="underline-tab-asACDJHq size-small-asACDJHq">Visibility</button><button aria-hidden="true" tabindex="-1" class="underline-tab-asACDJHq size-small-asACDJHq fake-asACDJHq">More<span class="arrow-icon-b2FB_70X size-small-b2FB_70X"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" width="18" height="18"><path fill="currentColor" d="M5.5 6.44a.75.75 0 1 0-1 1.12l1-1.12zM9 10.5l-.5.56c.29.25.71.25 1 0L9 10.5zm4.5-2.94a.75.75 0 0 0-1-1.12l1 1.12zm-9 0l4 3.5 1-1.12-4-3.5-1 1.12zm5 3.5l4-3.5-1-1.12-4 3.5 1 1.12z"></path></svg></span></button></div></div></div>

now is like

<div class="scrollWrap-Rf5MOAG5"><div class="headerBottomSeparator-Rf5MOAG5"></div><div class="wrapOverflow-qKQlcmkd"><div class="wrap-qKQlcmkd"><div class="scrollWrap-qKQlcmkd noScrollBar-qKQlcmkd"><div class="tabsWrap-Rf5MOAG5"><div class="tabs-Rf5MOAG5 tabs-g47ZTMzc"><div class="tab-Rf5MOAG5 tab-g47ZTMzc active-g47ZTMzc" data-type="tab-item" data-value="inputs" data-name="tab-item-inputs">Inputs</div><div class="tab-Rf5MOAG5 withHover-Rf5MOAG5 tab-g47ZTMzc" data-type="tab-item" data-value="properties" data-name="tab-item-properties">Properties</div><div class="tab-Rf5MOAG5 withHover-Rf5MOAG5 tab-g47ZTMzc" data-type="tab-item" data-value="style" data-name="tab-item-style">Style</div><div class="tab-Rf5MOAG5 withHover-Rf5MOAG5 tab-g47ZTMzc" data-type="tab-item" data-value="visibilities" data-name="tab-item-visibilities">Visibility</div><div class="slider-g47ZTMzc slider-n4RgAWzv" style="transform: translateX(6px); width: 72px; opacity: 1;"><div class="inner-n4RgAWzv"></div></div></div></div></div><div class="scrollLeft-qKQlcmkd"><div class="iconWrap-qKQlcmkd"><span class="icon-qKQlcmkd"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 10" width="20" height="10"><path fill="none" stroke="currentColor" stroke-width="1.5" d="M2 1l8 8 8-8"></path></svg></span></div></div><div class="scrollRight-qKQlcmkd"><div class="iconWrap-qKQlcmkd"><span class="icon-qKQlcmkd"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 10" width="20" height="10"><path fill="none" stroke="currentColor" stroke-width="1.5" d="M2 1l8 8 8-8"></path></svg></span></div></div></div></div></div>

**Comment by epixia** [comment]
I can confirm this is an issue on my side too

**Comment by epixia** [comment]
Thinking is has something to do with :  selector.js
    
    tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]',
    tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',

**Comment by Quetzalquatl** [comment]
Change the lines in the selector.js file as follows. then remove the extension and manually reinstall the extension in the folder where the file was changed.

tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]',
tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',

to :
tabInput: '#inputs',
tabInputActive: '#inputs',

**Comment by VincenzoUrso** [comment]
I did that but now the error is "could not find any strategy with parameters among...."

**Comment by Quetzalquatl** [comment]
@VincenzoUrso i check again...

**Comment by dangquang1506** [comment]
Also do i, got that notify. Now cannot test my indicator. What can i do now bro?

**Comment by dangquang1506** [comment]
Is this notify come from TradingView updated their code or our internal problem? Sorry i just newbie :D

**Comment by MrDenfish** [comment]
This happens when TV updates their code. Usually it takes a few days to amend the extension.

**Comment by akumidv** [comment]
Error reproduced and fixed. I'm checking version before publish. I'll send it to Google WebStore in an few hours. Probably on weekend or on Monday it will be published.

**Comment by stefantabakovq** [comment]
> Error reproduced and fixed. I'm checking version before publish. I'll send it to Google WebStore in an few hours. Probably on weekend or on Monday it will be published.

Could you share commit of the fix so that we can use before Chrome publishes? Thank you for all!

**Comment by Quetzalquatl** [comment]
workaround:
Change these lines in the selector.js file as follows;
tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]',
tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',

new version :
tabInput: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
tabInputActive: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]:nth-child(1)',

note: before running the extension, you need to select the inputs option in the strategy window. (The "tabInputActive" on the top line doesn't work properly. I'll share it here when the problem is resolved)

**Comment by stefantabakovq** [comment]
> workaround: Change these lines in the selector.js file as follows; tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]', tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',
> 
> new version : tabInput: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]', tabInputActive: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]:nth-child(1)',
> 
> note: before running the extension, you need to select the inputs option in the strategy window. (The "tabInputActive" on the top line doesn't work properly. I'll share it here when the problem is resolved)

I belive you need to have :: instead of a single : at `button[id="inputs"]:nth-child(1)`

**Comment by hodlbe** [comment]
Work for me:
change 3 selectors in selector.js
`
tabInput: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
tabInputActive: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
tabProperties: 'div[data-name="indicator-properties-dialog"] button#properties',
`

**Comment by stefantabakovq** [comment]
> Work for me: change 3 selectors in selector.js
> 
> tabInput: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
> 
> tabInputActive: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
> 
> tabProperties: 'div[data-name="indicator-properties-dialog"] button#properties',

Mashallah the missing piece, it works! Thank you!

**Comment by MrDenfish** [comment]
👍🏼 - Thanks back up and running...

**Comment by SlUlF** [comment]
[TradingAssistant.zip](https://github.com/akumidv/tradingview-assistant-chrome-extension/files/11182300/TradingAssistant.zip)

For the people who can't wait to get the official fixed version, you can download it from the link :)

**Comment by B0gdan2K** [comment]
Hi guys, the extesion is still not working, how to edit selector.js or to instal the files provided above?

Thank you!

**Comment by akumidv** [comment]
All these problem was fixed in v.2.5. Today I've sent to publishing in Google WebStore version 2.6. Can you check it?

**Comment by B0gdan2K** [comment]
Hi friend,
it does not work, I have removed the extension an added again to the browser, closed and opened the browser again, still doesn`t work.
Thank you!
Popescu George Bogdan,Kunden Broker S.A.,
Sucursala B1, cod 1907,0732976252

 

    On Wednesday, April 19, 2023 at 06:51:48 AM GMT+3, Andrei Kuminov ***@***.***> wrote:  
 
 


All these problem was fixed in v.2.5. Today I've sent to publishing in Google WebStore version 2.6. Can you check it?

**Comment by dangquang1506** [comment]
> All these problem was fixed in v.2.5. Today I've sent to publishing in Google WebStore version 2.6. Can you check it?

Hi, can you help me to edit the code that will automatic download the result after backtest. Without click on this popup?
<img width="803" alt="image" src="https://user-images.githubusercontent.com/92879610/234831500-f419a9e5-c877-4cd4-a800-35bc71f4b9f4.png">
I think it will me more convenience for us. Many thanks and best regards

**Comment by akumidv** [comment]
> > All these problem was fixed in v.2.5. Today I've sent to publishing in Google WebStore version 2.6. Can you check it?
> 
> Hi, can you help me to edit the code that will automatic download the result after backtest. Without click on this popup? <img alt="image" width="803" src="https://user-images.githubusercontent.com/92879610/234831500-f419a9e5-c877-4cd4-a800-35bc71f4b9f4.png"> I think it will me more convenience for us. Many thanks and best regards

I'll add this to next version

**Comment by akumidv** [comment]
This will be in next published v.2.9.0 version (implemented in current version in repository)
